openapi: 3.0.2
info:
  description: >
    # Introduction

    a customer relation manager for a kayak rental shop


    ## Response Structure


    ### Success Property

    In responses from this API, you will often encounter the success property.
    This property indicates whether the request was successful or not. If
    success is true, it means the request was successful, and additional
    information may be included in the response. If success is false, it
    indicates an error occurred, and you should check the error property for
    details.


    ### Data Property

    The data property contains the main payload of a successful response. It
    typically includes the requested information, such as customer data or other
    relevant data objects.


    ### Meta Property

    In paginated responses, you may encounter the meta property. This property
    contains metadata about the response, including pagination details and
    additional context information.


    ### Error Property

    If an error occurs during a request, the error property will be present in
    the response. It includes sub-properties, each associated with a request
    parameter or error type, and an array of strings describing encountered
    issues.


    Please refer to individual endpoint documentation for specific details on
    the response structure for each API endpoint.
  title: Customer Relation Manager API
  version: 1.0.0
paths:
  /api/v1/customers:
    $ref: paths/api_v1_customers.yaml
  /api/v1/customers/{id}:
    $ref: paths/api_v1_customers_{id}.yaml
